homeYdle:
    pattern:  /
    defaults: { _controller: YdleHubBundle:Home:index }

    
pagesAbout:
    pattern:  /pages/about
    defaults: { _controller: YdleHubBundle:Pages:index }
    
    
configDashboard:
    pattern:  /conf/dashboard
    defaults: { _controller: YdleHubBundle:Config:dashboard }
    

Populate:
    pattern:  /conf/populate
    defaults: { _controller: YdleHubBundle:Config:populate }
    

    
  
  
  
configYdle:
    pattern:  /conf
    defaults: { _controller: YdleHubBundle:Config:index }
configTypeRoom:
  pattern: /conf/typeroom
  defaults: { _controller: YdleHubBundle:Config:typeroom }
configTypeRoomForm:
  pattern: /conf/typeroom/form/{type}
  defaults: { _controller: YdleHubBundle:Config:typeroomForm, type:0 }
configTypeNode:
  pattern: /conf/typenode
  defaults: { _controller: YdleHubBundle:Config:typenode }
configTypeNodeForm:
  pattern: /conf/typenode/form/{type}
  defaults: { _controller: YdleHubBundle:Config:typenodeForm, type:0 }
  
################
#    Nodes     #
################    
nodes:
    pattern:  /nodes
    defaults: { _controller: YdleHubBundle:Nodes:index }
nodesForm:
  pattern: /nodes/form/{node}
  defaults: { _controller: YdleHubBundle:Nodes:nodesForm, node:0 }
submitNodeForm:
  pattern: /nodes/form/{node}/submit
  defaults: { _controller: YdleHubBundle:Nodes:submitNodeForm, node:0 } 
 
##################
#  Type Sensors  #
##################
configTypeSensor:
    pattern:  /conf/typesensor/{type}
    defaults: { _controller: YdleHubBundle:Config:typesensor, type:0 }
configTypeSensorActivation:
    pattern:  /conf/typesensor/activation/{type}/{active}
    defaults: { _controller: YdleHubBundle:Config:typesensoractivation, type:0, active:0 } 
configTypeSensorDelete:
    pattern:  /conf/typesensor/delete/{type}
    defaults: { _controller: YdleHubBundle:Config:typesensordelete, type:0 } 
  
################
#    Rooms     #
################  
rooms:
  pattern:  /rooms
  defaults: { _controller: YdleHubBundle:Room:index }
roomForm:
  pattern: /room/form/{room}
  defaults: { _controller: YdleHubBundle:Room:roomForm, room:0 }
submitRoomForm:
  pattern: /room/form/{room}/submit
  defaults: { _controller: YdleHubBundle:Room:submitRoomForm, room:0 }
roomDetail:
  pattern: /room/detail/{room}
  defaults: { _controller: YdleHubBundle:Room:roomDetail, room:0 }
  
  
################
#     Logs     #
################
logs:
    pattern:  /logs
    defaults: { _controller: YdleHubBundle:Logs:index }
 
resetlogs:
    pattern: /logs/reset
    defaults: { _controller: YdleHubBundle:Logs:reset }
      
