parameters:
  ydle.data.manager.class: Ydle\HubBundle\Manager\DataManager
  ydle.logs.manager.class: Ydle\HubBundle\Manager\LogsManager
  ydle.logs.entity.class: Ydle\HubBundle\Entity\Logs
  ydle.roomtype.manager.class: Ydle\HubBundle\Manager\RoomTypeManager
  ydle.roomtype.entity.class: Ydle\HubBundle\Entity\RoomType
  ydle.room.manager.class: Ydle\HubBundle\Manager\RoomManager
  ydle.room.entity.class: Ydle\HubBundle\Entity\Room
  ydle.node.manager.class: Ydle\HubBundle\Manager\NodeManager
  ydle.node.entity.class: Ydle\HubBundle\Entity\Node
  ydle.nodetype.manager.class: Ydle\HubBundle\Manager\NodeTypeManager
  ydle.nodetype.entity.class: Ydle\HubBundle\Entity\NodeType
  ydle.validator.unique.master.class: Ydle\HubBundle\Validator\Constraints\IsMasterValidator

  ydle.settings.roomtype.controller.class: Ydle\HubBundle\Controller\RestRoomTypeController
  ydle.settings.nodetype.controller.class: Ydle\HubBundle\Controller\RestNodeTypeController
  ydle.settings.logs.controller.class: Ydle\HubBundle\Controller\RestLogsController
  ydle.settings.nodes.controller.class: Ydle\HubBundle\Controller\RestNodeController
  ydle.settings.rooms.controller.class: Ydle\HubBundle\Controller\RestRoomController

services:
  ydle.logger:
    class: %ydle.logs.manager.class%
    arguments: [%ydle.logs.entity.class%, "@doctrine"]
  ydle.data.manager:
    class: %ydle.data.manager.class%
    arguments:
      entityManager: "@doctrine.orm.entity_manager"
  ydle.roomtype.manager:
    class: %ydle.roomtype.manager.class%
    arguments: [%ydle.roomtype.entity.class%, "@doctrine"]
  ydle.room.manager:
    class: %ydle.room.manager.class%
    arguments: [%ydle.room.entity.class%, "@doctrine"]
  ydle.nodetype.manager:
    class: %ydle.nodetype.manager.class%
    arguments: [%ydle.nodetype.entity.class%, "@doctrine"]
  ydle.node.manager:
    class: %ydle.node.manager.class%
    arguments: [%ydle.node.entity.class%, "@doctrine"]
  validator.unique.ismaster:
    class: %ydle.validator.unique.master.class%
    arguments: ["@service_container"]
    tags:
      - { name: "validator.constraint_validator", alias: master_validator }

  ydle.settings.roomtype.controller:
    class: %ydle.settings.roomtype.controller.class%
    arguments: ["@ydle.roomtype.manager", "@service_container"]
  ydle.settings.nodetype.controller:
    class: %ydle.settings.nodetype.controller.class%
    arguments: ["@ydle.nodetype.manager", "@service_container"]
  ydle.settings.logs.controller:
    class: %ydle.settings.logs.controller.class%
    arguments: ["@ydle.logger", "@service_container"]
  ydle.settings.nodes.controller:
    class: %ydle.settings.nodes.controller.class%
    arguments: ["@ydle.node.manager", "@service_container"]
  ydle.settings.rooms.controller:
    class: %ydle.settings.rooms.controller.class%
    arguments: ["@ydle.room.manager", "@service_container"]
