<?php

namespace Ydle\HubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeDataRepository extends EntityRepository
{
    
    public function findByRoom($params)
    {
        $qb = $this->createQueryBuilder("d");
        $qb->where('1=1');
        
        $qb->join('d.node', 'n')
           ->andWhere('n.room = :roomid')
                ->setParameter('roomid', $params['room_id'])
           ->andWhere('d.node = :nodeid')
                ->setParameter('nodeid', $params['node_id'])
           ->andWhere('d.type = :type')
                ->setParameter('type', $params['type_id'])
           ->andWhere('d.created > :startdate')
                ->setParameter('startdate', $params['start_date'])
           ->orderBy('d.created')
        ;
        
        
        $q = $qb->getQuery();
        try {
            if(isset($params['querybuilder'])){
                return $qb;
            } else {
                return $q->getResult();
            }
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function getLastData($roomId)
    {
        $qb = $this->createQueryBuilder("d")
                ->join('d.node', 'n')
                ->join('d.type', 't')
                ->where('n.room = :roomid')
                    ->setParameter('roomid', $roomId)
                ->andWhere('n.isActive = 1')
                ->groupBy('d.type')
                ->orderBy('d.created', 'DESC')
        ;
        
        try {
            return $qb->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
